### ISSUE TITLE
PNG, PDF export? How about SVG?

### ISSUE THREAD

**Issue by Robert-M-Muench** [mark-when/markwhen#94]
Seems I'm missing this feature. Where do I find it?

And plans to export to SVG?

**Comment by kochrt** [comment]
It's coming back... eventually. SVG will actually probably be first. I recently overhauled the layout so that it was elements are positioned absolutely instead of hierarchically, which should enable svg quite nicely. And then PNG/PDF after that would be trivial (famous last words).

Previously PNG/PDF exports were done by recreating the timeline server-side in a chrome instance and then taking a screenshot. I wanted to get away from that.

**Comment by Robert-M-Muench** [comment]
Great! I'm ready to test it :-)

**Comment by kochrt** [comment]
Added SVG/PNG under the export section.

Sections aren't supported nor are a bunch of other things but it's a start

<img width="300" alt="Screen Shot 2023-01-12 at 6 00 03 PM" src="https://user-images.githubusercontent.com/10823320/212199525-cb5498e7-d39b-4e44-9b8a-19ba72b831a9.png">

<img width="821" alt="Screen Shot 2023-01-12 at 6 00 11 PM" src="https://user-images.githubusercontent.com/10823320/212199530-d585c8c1-a71e-41d0-ac8f-24ffda8698d3.png">
